_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 16
center_readout:
    value: false
exp_var_thresholds:
    value:
        - 0.25
        - 0.25
        - 0.25
feat_ext_type:
    value: resnet3d
first_frame_only:
    value: false
flatten_time:
    value: true
l2_weight:
    value: 0
layer:
    value: layer1
lr:
    value: 0.001
modality:
    value: video
model_name:
    value: unfrozen pretrained
num_epochs:
    value: 40
pool_size:
    value: 4
pool_stride:
    value: 2
pos:
    value:
        - 400
        - 180
save:
    value: true
session_id:
    value: "083024"
stim_dur_ms:
    value: 200
stim_shape:
    value:
        - 1
        - 3
        - 5
        - 32
        - 32
stim_size:
    value: 32
use_pool:
    value: true
use_pretrained:
    value: true
use_sigma:
    value: true
wandb:
    value: true
win_size:
    value: 240
